-- =====================================================
-- Seed additional Lagos events (v2)
--
-- Layers more variety on top of the original 10-event seed so the
-- consumer Events screen feels populated across every filter chip.
--
-- Each row gets a stable `external_id` so this migration is idempotent
-- via the UNIQUE(source, external_id) constraint — re-running it (or
-- a remote sync) will not double-insert.
--
-- All rows use source='manual' so they appear immediately without
-- waiting on the fetch-lagos-events sync.
-- =====================================================

INSERT INTO public.events (
  external_id,
  title, short_description, description,
  category, event_type,
  start_date, end_date, timezone,
  venue_name, venue_address, location,
  is_free, ticket_price_min, ticket_price_max, currency,
  ticket_url, organizer_name,
  image_url,
  source, is_active, is_published, is_featured, status
)
VALUES

-- ── Nightlife ─────────────────────────────────────────
('gidi-seed-v2-nl-001',
  'Quilox VIP Saturdays',
  'The flagship Saturday at Lagos''s most iconic club.',
  'Quilox VIP Saturdays brings together the biggest names in Lagos nightlife with bottle service, surprise celebrity appearances, and DJ sets that run until 5am.',
  'Nightlife', 'club night',
  (NOW() + INTERVAL '3 days')::timestamptz,
  (NOW() + INTERVAL '3 days' + INTERVAL '7 hours')::timestamptz,
  'Africa/Lagos',
  'Quilox Club', 'Ozumba Mbadiwe Avenue, Victoria Island', 'Victoria Island, Lagos',
  false, 10000, 50000, 'NGN',
  'https://www.nairabox.com/', 'Quilox',
  'https://images.unsplash.com/photo-1571266028243-d220c6a3a93f?w=800&q=80',
  'manual', true, true, false, 'upcoming'),

('gidi-seed-v2-nl-002',
  'Tequila Tuesday at Hard Rock Lekki',
  'Half-priced tequila, live band, and the best margaritas in Lagos.',
  'Every Tuesday at Hard Rock Cafe Lekki: half-priced tequila shots, classic and signature margaritas, and a rotating roster of live bands playing Afrobeats, Latin, and rock fusion.',
  'Nightlife', 'bar night',
  (NOW() + INTERVAL '6 days')::timestamptz,
  (NOW() + INTERVAL '6 days' + INTERVAL '5 hours')::timestamptz,
  'Africa/Lagos',
  'Hard Rock Cafe Lekki', 'Plot 4, Admiralty Way, Lekki Phase 1', 'Lekki, Lagos',
  false, 0, 0, 'NGN',
  'https://www.hardrock.com/', 'Hard Rock Cafe',
  'https://images.unsplash.com/photo-1514933651103-005eec06c04b?w=800&q=80',
  'manual', true, true, false, 'upcoming'),

('gidi-seed-v2-nl-003',
  'Detty December Pre-Party',
  'Kick off Detty December early with the city''s biggest pre-party.',
  'The official Detty December pre-party — three rooms, six DJs, and an open bar for the first hour. Dress code: glitter, gold, and good vibes.',
  'Nightlife', 'party',
  (NOW() + INTERVAL '14 days')::timestamptz,
  (NOW() + INTERVAL '14 days' + INTERVAL '8 hours')::timestamptz,
  'Africa/Lagos',
  'The Cocoon Lounge', 'Plot 4, Bishop Aboyade Cole, Victoria Island', 'Victoria Island, Lagos',
  false, 15000, 35000, 'NGN',
  'https://www.tix.africa/', 'Detty Events',
  'https://images.unsplash.com/photo-1545128485-c400e7702796?w=800&q=80',
  'manual', true, true, false, 'upcoming'),

('gidi-seed-v2-nl-004',
  'Rooftop Sundowner Sessions',
  'Sunset cocktails and Afro-house on a Victoria Island rooftop.',
  'Every Friday from 5pm: sunset cocktails, Afro-house DJ sets, and 360° views of Lagos lagoon. Limited capacity, RSVP recommended.',
  'Nightlife', 'rooftop',
  (NOW() + INTERVAL '8 days')::timestamptz,
  (NOW() + INTERVAL '8 days' + INTERVAL '6 hours')::timestamptz,
  'Africa/Lagos',
  'Eko Hotel Rooftop Bar', 'Plot 1415 Adetokunbo Ademola, Victoria Island', 'Victoria Island, Lagos',
  false, 8000, 12000, 'NGN',
  'https://www.nairabox.com/', 'Sundowner Lagos',
  'https://images.unsplash.com/photo-1551024601-bec78aea704b?w=800&q=80',
  'manual', true, true, false, 'upcoming'),

-- ── Food & Dining ─────────────────────────────────────
('gidi-seed-v2-fd-001',
  'Suya Festival Lagos',
  'A celebration of Nigeria''s favourite street food.',
  'Over 30 of the best suya vendors in Lagos, from classic beef to ram, gizzard, and seafood variations. Live cooking demos, suya pairing classes, and Nigerian beer on tap.',
  'Food & Dining', 'festival',
  (NOW() + INTERVAL '7 days')::timestamptz,
  (NOW() + INTERVAL '8 days')::timestamptz,
  'Africa/Lagos',
  'Tafawa Balewa Square', 'Race Course Road, Lagos Island', 'Lagos Island, Lagos',
  false, 2000, 2000, 'NGN',
  'https://www.nairabox.com/', 'Suya Fest Co.',
  'https://images.unsplash.com/photo-1529193591184-b1d58069ecdd?w=800&q=80',
  'manual', true, true, true, 'upcoming'),

('gidi-seed-v2-fd-002',
  'Wine & Vine Tasting Night',
  'Premium wine tasting hosted by a Master Sommelier.',
  'Sample 12 premium wines paired with small plates from chef Tunde Wey. Hosted by Master Sommelier Bola Adekunle. Includes a takeaway tasting journal.',
  'Food & Dining', 'tasting',
  (NOW() + INTERVAL '12 days')::timestamptz,
  (NOW() + INTERVAL '12 days' + INTERVAL '3 hours')::timestamptz,
  'Africa/Lagos',
  'The Wine Cellar', '23 Bourdillon Road, Ikoyi', 'Ikoyi, Lagos',
  false, 35000, 50000, 'NGN',
  'https://www.tix.africa/', 'Wine & Vine',
  'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=800&q=80',
  'manual', true, true, false, 'upcoming'),

('gidi-seed-v2-fd-003',
  'Brunch on the Marina',
  'Bottomless brunch with live saxophone, lagoon views.',
  'Every Sunday: bottomless mimosas, eggs benedict, and a live saxophone trio. Best brunch in Lagos for two years running.',
  'Food & Dining', 'brunch',
  (NOW() + INTERVAL '5 days')::timestamptz,
  (NOW() + INTERVAL '5 days' + INTERVAL '4 hours')::timestamptz,
  'Africa/Lagos',
  'Bottega Italian Restaurant', '12 Marina Road, Lagos Island', 'Lagos Island, Lagos',
  false, 18000, 18000, 'NGN',
  'https://www.nairabox.com/', 'Bottega Lagos',
  'https://images.unsplash.com/photo-1533089860892-a7c6f0a88666?w=800&q=80',
  'manual', true, true, false, 'upcoming'),

('gidi-seed-v2-fd-004',
  'Jollof Wars 2026',
  'Nigeria''s most-loved cook-off returns: who makes the best jollof?',
  'Twelve of Lagos''s top chefs face off in the annual Jollof Wars. Audience tastes and votes. Winner takes home the Golden Pot.',
  'Food & Dining', 'cook-off',
  (NOW() + INTERVAL '21 days')::timestamptz,
  (NOW() + INTERVAL '21 days' + INTERVAL '5 hours')::timestamptz,
  'Africa/Lagos',
  'Muri Okunola Park', 'Victoria Island, Lagos', 'Victoria Island, Lagos',
  false, 3500, 3500, 'NGN',
  'https://www.tix.africa/', 'Jollof Wars',
  'https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?w=800&q=80',
  'manual', true, true, false, 'upcoming'),

('gidi-seed-v2-fd-005',
  'Lagos Coffee Week',
  'A week celebrating Lagos''s booming specialty coffee scene.',
  'Lagos Coffee Week brings together roasters, baristas, and coffee lovers. Cupping sessions, latte art competitions, and a coffee market featuring beans from across West Africa.',
  'Food & Dining', 'festival',
  (NOW() + INTERVAL '24 days')::timestamptz,
  (NOW() + INTERVAL '30 days')::timestamptz,
  'Africa/Lagos',
  'Civic Centre', 'Ozumba Mbadiwe Avenue, Victoria Island', 'Victoria Island, Lagos',
  false, 1500, 5000, 'NGN',
  'https://www.eventbrite.com/', 'Lagos Coffee Co.',
  'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800&q=80',
  'manual', true, true, false, 'upcoming'),

-- ── Technology ────────────────────────────────────────
('gidi-seed-v2-tc-001',
  'AI Lagos Conference 2026',
  'Africa''s largest AI and machine learning conference.',
  'AI Lagos brings together engineers, researchers, and founders building the future of AI in Africa. Keynotes from leading labs, hands-on workshops, and a startup showcase.',
  'Technology', 'conference',
  (NOW() + INTERVAL '15 days')::timestamptz,
  (NOW() + INTERVAL '17 days')::timestamptz,
  'Africa/Lagos',
  'Landmark Event Centre', 'Water Corporation Drive, Oniru', 'Lekki, Lagos',
  false, 25000, 75000, 'NGN',
  'https://www.eventbrite.com/', 'AI Lagos',
  'https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=800&q=80',
  'manual', true, true, true, 'upcoming'),

('gidi-seed-v2-tc-002',
  'Startup Pitch Night Lagos',
  'Six startups, five minutes each, one winning cheque.',
  'Six early-stage Lagos startups pitch to a panel of VCs and angel investors. The winner takes home ₦5M in seed funding and three months at Workspace Hub.',
  'Technology', 'pitch',
  (NOW() + INTERVAL '9 days')::timestamptz,
  (NOW() + INTERVAL '9 days' + INTERVAL '3 hours')::timestamptz,
  'Africa/Lagos',
  'Workspace Hub', '34 Awolowo Road, Ikoyi', 'Ikoyi, Lagos',
  true, 0, 0, 'NGN',
  'https://www.eventbrite.com/', 'Workspace Hub',
  'https://images.unsplash.com/photo-1559136555-9303baea8ebd?w=800&q=80',
  'manual', true, true, false, 'upcoming'),

('gidi-seed-v2-tc-003',
  'Web3 Lagos Meetup',
  'The monthly meetup for Web3 builders in Lagos.',
  'Hands-on demos, lightning talks, and networking with the most active Web3 community in West Africa. November''s topic: Layer 2s and the African use case.',
  'Technology', 'meetup',
  (NOW() + INTERVAL '4 days')::timestamptz,
  (NOW() + INTERVAL '4 days' + INTERVAL '3 hours')::timestamptz,
  'Africa/Lagos',
  'Co-Creation Hub', '294 Herbert Macaulay Way, Yaba', 'Yaba, Lagos',
  true, 0, 0, 'NGN',
  'https://www.eventbrite.com/', 'Web3 Lagos',
  'https://images.unsplash.com/photo-1639762681485-074b7f938ba0?w=800&q=80',
  'manual', true, true, false, 'upcoming'),

-- ── Arts & Culture ────────────────────────────────────
('gidi-seed-v2-ac-001',
  'Lagos Photo Festival',
  'Africa''s leading international art photography festival.',
  'Now in its 16th year, Lagos Photo brings together international and Nigerian photographers exploring identity, urban life, and the African diaspora. Open daily 10am-7pm.',
  'Arts & Culture', 'exhibition',
  (NOW() + INTERVAL '16 days')::timestamptz,
  (NOW() + INTERVAL '40 days')::timestamptz,
  'Africa/Lagos',
  'African Artists'' Foundation', '23 Olusegun Aina Street, Parkview', 'Ikoyi, Lagos',
  false, 1000, 2000, 'NGN',
  'https://www.tix.africa/', 'AAF Lagos',
  'https://images.unsplash.com/photo-1452587925148-ce544e77e70d?w=800&q=80',
  'manual', true, true, false, 'upcoming'),

('gidi-seed-v2-ac-002',
  'Yoruba Cinema Night',
  'A curated screening of contemporary Yoruba indie films.',
  'Three Yoruba indie films screen back-to-back, followed by a director Q&A. Curated by filmmaker Kemi Adetiba in partnership with Filmhouse Lagos.',
  'Arts & Culture', 'film',
  (NOW() + INTERVAL '11 days')::timestamptz,
  (NOW() + INTERVAL '11 days' + INTERVAL '4 hours')::timestamptz,
  'Africa/Lagos',
  'Filmhouse IMAX Lekki', 'Lekki Phase 1', 'Lekki, Lagos',
  false, 4000, 6000, 'NGN',
  'https://www.tix.africa/', 'Filmhouse Cinemas',
  'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?w=800&q=80',
  'manual', true, true, false, 'upcoming'),

('gidi-seed-v2-ac-003',
  'Nike Art Gallery: Open House',
  'Free open house at Lagos''s largest private art gallery.',
  'Tour eight floors of contemporary African art, meet the artists, and watch live painting demos. Free entry, family-friendly.',
  'Arts & Culture', 'gallery',
  (NOW() + INTERVAL '6 days')::timestamptz,
  (NOW() + INTERVAL '6 days' + INTERVAL '6 hours')::timestamptz,
  'Africa/Lagos',
  'Nike Art Gallery', '2 Elegushi Beach Road, Lekki', 'Lekki, Lagos',
  true, 0, 0, 'NGN',
  'https://www.eventbrite.com/', 'Nike Art Foundation',
  'https://images.unsplash.com/photo-1531297484001-80022131f5a1?w=800&q=80',
  'manual', true, true, false, 'upcoming'),

-- ── Entertainment ─────────────────────────────────────
('gidi-seed-v2-en-001',
  'Wizkid Live at Eko Hotel',
  'Wizkid returns to Lagos for a one-night-only homecoming show.',
  'After a global tour, Wizkid headlines a special homecoming show at Eko Hotel. Limited tickets, official merch on sale at the venue, doors at 7pm.',
  'Entertainment', 'concert',
  (NOW() + INTERVAL '28 days')::timestamptz,
  (NOW() + INTERVAL '28 days' + INTERVAL '5 hours')::timestamptz,
  'Africa/Lagos',
  'Eko Hotel Convention Centre', 'Plot 1415 Adetokunbo Ademola, VI', 'Victoria Island, Lagos',
  false, 25000, 250000, 'NGN',
  'https://www.tix.africa/', 'Starboy Entertainment',
  'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=800&q=80',
  'manual', true, true, true, 'upcoming'),

('gidi-seed-v2-en-002',
  'Bovi: The Lagos Special',
  'Stand-up comedy with Nigeria''s favourite funny man.',
  'Bovi takes the stage at Terra Kulture for an intimate stand-up special — material recorded for his upcoming Netflix special.',
  'Entertainment', 'comedy',
  (NOW() + INTERVAL '13 days')::timestamptz,
  (NOW() + INTERVAL '13 days' + INTERVAL '2 hours')::timestamptz,
  'Africa/Lagos',
  'Terra Kulture', 'Plot 1376 Tiamiyu Savage Street, VI', 'Victoria Island, Lagos',
  false, 8000, 20000, 'NGN',
  'https://www.tix.africa/', 'Bovi Live',
  'https://images.unsplash.com/photo-1543007630-9710e4a00a20?w=800&q=80',
  'manual', true, true, false, 'upcoming'),

('gidi-seed-v2-en-003',
  'Big Brother Naija Watch Party',
  'The official BBN finale viewing party — live broadcast on big screen.',
  'Lagos''s biggest BBN watch party: live broadcast on a 30-ft screen, themed cocktails, themed costumes encouraged, and a midnight reveal party.',
  'Entertainment', 'watch party',
  (NOW() + INTERVAL '17 days')::timestamptz,
  (NOW() + INTERVAL '17 days' + INTERVAL '6 hours')::timestamptz,
  'Africa/Lagos',
  'Hard Rock Cafe Lekki', 'Plot 4, Admiralty Way, Lekki Phase 1', 'Lekki, Lagos',
  false, 5000, 8000, 'NGN',
  'https://www.nairabox.com/', 'Hard Rock Cafe',
  'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=800&q=80',
  'manual', true, true, false, 'upcoming'),

-- ── Concert (new category) ────────────────────────────
('gidi-seed-v2-cn-001',
  'Asake Live at the Beach',
  'Asake performs an exclusive beachside show at Landmark.',
  'Asake brings his signature sound to a special beach show. Backed by a 12-piece live band, sunset start time, and a fireworks finale.',
  'Concert', 'concert',
  (NOW() + INTERVAL '22 days')::timestamptz,
  (NOW() + INTERVAL '22 days' + INTERVAL '5 hours')::timestamptz,
  'Africa/Lagos',
  'Landmark Beach', 'Water Corporation Drive, Oniru', 'Lekki, Lagos',
  false, 20000, 150000, 'NGN',
  'https://www.tix.africa/', 'YBNL',
  'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=800&q=80',
  'manual', true, true, false, 'upcoming'),

('gidi-seed-v2-cn-002',
  'Tems: Acoustic Set',
  'An intimate stripped-back evening with Tems.',
  'Tems performs an acoustic set of her hits plus previews from her upcoming album. Strictly limited capacity — first-come tickets only.',
  'Concert', 'acoustic',
  (NOW() + INTERVAL '19 days')::timestamptz,
  (NOW() + INTERVAL '19 days' + INTERVAL '2 hours')::timestamptz,
  'Africa/Lagos',
  'The Theatre', 'Eko Hotel, Victoria Island', 'Victoria Island, Lagos',
  false, 30000, 80000, 'NGN',
  'https://www.tix.africa/', 'Leading Vibe',
  'https://images.unsplash.com/photo-1429962714451-bb934ecdc4ec?w=800&q=80',
  'manual', true, true, false, 'upcoming'),

('gidi-seed-v2-cn-003',
  'Burna Boy: One Night Only',
  'The African Giant returns with a sold-out homecoming show.',
  'Burna Boy headlines the largest concert of the year. Full African Giant production, three-hour set, and surprise guests confirmed.',
  'Concert', 'concert',
  (NOW() + INTERVAL '35 days')::timestamptz,
  (NOW() + INTERVAL '35 days' + INTERVAL '6 hours')::timestamptz,
  'Africa/Lagos',
  'Tafawa Balewa Square', 'Race Course Road, Lagos Island', 'Lagos Island, Lagos',
  false, 35000, 350000, 'NGN',
  'https://www.tix.africa/', 'Spaceship Records',
  'https://images.unsplash.com/photo-1501386761578-eac5c94b800a?w=800&q=80',
  'manual', true, true, true, 'upcoming'),

-- ── Sports (new category) ─────────────────────────────
('gidi-seed-v2-sp-001',
  'Lagos City Marathon',
  'Africa''s largest road race — 42 km through the heart of Lagos.',
  'Run with 100,000 fellow runners from Lagos Island to National Stadium. Full marathon, half-marathon, and 10K. Charity entries welcome.',
  'Sports', 'marathon',
  (NOW() + INTERVAL '26 days')::timestamptz,
  (NOW() + INTERVAL '26 days' + INTERVAL '6 hours')::timestamptz,
  'Africa/Lagos',
  'National Stadium', 'Surulere', 'Surulere, Lagos',
  false, 5000, 15000, 'NGN',
  'https://www.lagoscitymarathon.com/', 'Lagos State Government',
  'https://images.unsplash.com/photo-1461896836934-ffe607ba8211?w=800&q=80',
  'manual', true, true, false, 'upcoming'),

('gidi-seed-v2-sp-002',
  'Eko Atlantic Polo Cup',
  'Lagos''s premier polo tournament with champagne and canapés.',
  'Watch four teams battle for the Eko Atlantic Cup. Champagne reception, gourmet food trucks, and a fashion runway during the half-time break.',
  'Sports', 'tournament',
  (NOW() + INTERVAL '20 days')::timestamptz,
  (NOW() + INTERVAL '20 days' + INTERVAL '5 hours')::timestamptz,
  'Africa/Lagos',
  'Lagos Polo Club', '1 Glover Road, Ikoyi', 'Ikoyi, Lagos',
  false, 15000, 50000, 'NGN',
  'https://www.tix.africa/', 'Eko Polo',
  'https://images.unsplash.com/photo-1532883261379-fff62a52e36e?w=800&q=80',
  'manual', true, true, false, 'upcoming'),

('gidi-seed-v2-sp-003',
  'Surfing Lagos Open',
  'Nigeria''s biggest surfing competition at Tarkwa Bay.',
  'Top surfers from across West Africa compete in the Open. Spectators welcome — bring sunscreen, leave with a tan.',
  'Sports', 'tournament',
  (NOW() + INTERVAL '32 days')::timestamptz,
  (NOW() + INTERVAL '33 days')::timestamptz,
  'Africa/Lagos',
  'Tarkwa Bay Beach', 'Tarkwa Bay', 'Lagos Island, Lagos',
  true, 0, 0, 'NGN',
  'https://www.eventbrite.com/', 'Surf Lagos',
  'https://images.unsplash.com/photo-1502680390469-be75c86b636f?w=800&q=80',
  'manual', true, true, false, 'upcoming'),

-- ── Comedy (new category) ─────────────────────────────
('gidi-seed-v2-cm-001',
  'AY Live: Lagos Tour',
  'AY Comedian headlines his return-home Lagos show.',
  'AY brings his Live tour back home with the full slate of regulars: Bovi, Basketmouth, I Go Dye, and special guests.',
  'Comedy', 'stand-up',
  (NOW() + INTERVAL '25 days')::timestamptz,
  (NOW() + INTERVAL '25 days' + INTERVAL '4 hours')::timestamptz,
  'Africa/Lagos',
  'Eko Hotel Convention Centre', 'Plot 1415 Adetokunbo Ademola, VI', 'Victoria Island, Lagos',
  false, 10000, 50000, 'NGN',
  'https://www.tix.africa/', 'AY Live',
  'https://images.unsplash.com/photo-1610890716171-6b1bb98ffd09?w=800&q=80',
  'manual', true, true, false, 'upcoming'),

('gidi-seed-v2-cm-002',
  'The Funny Bone Sundays',
  'Weekly stand-up showcase featuring rising Lagos comics.',
  'Every Sunday at Terra Kulture: five comedians, one hour, plenty of suya. Hosted by Akpororo.',
  'Comedy', 'stand-up',
  (NOW() + INTERVAL '5 days')::timestamptz,
  (NOW() + INTERVAL '5 days' + INTERVAL '2 hours')::timestamptz,
  'Africa/Lagos',
  'Terra Kulture', 'Plot 1376 Tiamiyu Savage Street, VI', 'Victoria Island, Lagos',
  false, 3500, 5000, 'NGN',
  'https://www.eventbrite.com/', 'Funny Bone Lagos',
  'https://images.unsplash.com/photo-1527224538127-2104bb71c51b?w=800&q=80',
  'manual', true, true, false, 'upcoming'),

-- ── Networking (new category) ─────────────────────────
('gidi-seed-v2-nw-001',
  'Lagos Business Brunch',
  'Monthly brunch for Lagos founders, operators, and investors.',
  'Curated table seating with founders, operators, and investors across fintech, e-commerce, and creative industries. Strictly limited capacity.',
  'Networking', 'brunch',
  (NOW() + INTERVAL '10 days')::timestamptz,
  (NOW() + INTERVAL '10 days' + INTERVAL '3 hours')::timestamptz,
  'Africa/Lagos',
  'Sky Restaurant', 'Eko Hotel, Victoria Island', 'Victoria Island, Lagos',
  false, 30000, 30000, 'NGN',
  'https://www.tix.africa/', 'Lagos Business Brunch',
  'https://images.unsplash.com/photo-1556761175-5973dc0f32e7?w=800&q=80',
  'manual', true, true, false, 'upcoming'),

('gidi-seed-v2-nw-002',
  'Female Founders Mixer',
  'A safe-space networking evening for women in tech.',
  'Quarterly mixer for female founders, operators, and investors across the Lagos tech ecosystem. Includes a panel + structured speed-networking.',
  'Networking', 'mixer',
  (NOW() + INTERVAL '14 days')::timestamptz,
  (NOW() + INTERVAL '14 days' + INTERVAL '3 hours')::timestamptz,
  'Africa/Lagos',
  'Workspace Hub', '34 Awolowo Road, Ikoyi', 'Ikoyi, Lagos',
  false, 5000, 5000, 'NGN',
  'https://www.eventbrite.com/', 'Female Founders Lagos',
  'https://images.unsplash.com/photo-1573164713988-8665fc963095?w=800&q=80',
  'manual', true, true, false, 'upcoming'),

-- ── Workshop (bonus — already has fallback image) ─────
('gidi-seed-v2-wk-001',
  'Photography Masterclass: Lagos Streets',
  'A weekend workshop on capturing Lagos street life.',
  'Award-winning photographer Logor leads a two-day workshop on street photography in Lagos. All skill levels welcome, lunch included on both days.',
  'Workshop', 'workshop',
  (NOW() + INTERVAL '18 days')::timestamptz,
  (NOW() + INTERVAL '19 days')::timestamptz,
  'Africa/Lagos',
  'African Artists'' Foundation', '23 Olusegun Aina Street, Parkview', 'Ikoyi, Lagos',
  false, 25000, 25000, 'NGN',
  'https://www.eventbrite.com/', 'AAF Lagos',
  'https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?w=800&q=80',
  'manual', true, true, false, 'upcoming')

ON CONFLICT (source, external_id) DO NOTHING;

-- =====================================================
-- Seed v2 complete: 28 additional Lagos events inserted
-- across Nightlife, Food & Dining, Technology, Arts &
-- Culture, Entertainment, Concert, Sports, Comedy,
-- Networking, and Workshop.
-- =====================================================
